---
title: "churn_classifier"
output: html_notebook
---
```{r}
library("dplyr")
library("magrittr")
```


```{r}
churn_df <- read.csv("data/churn_train.csv")

summary(churn_df)
```

Let's look at the percentage of `NA`s found in the dataset for all the variables 
```{r}
na_percentage <- function(df) {
  return (df %>%
            is.na() %>%
            colMeans() %>%
            sapply(function(x){
              return(sprintf("%.5f%%", x * 100))
            })
          )
}
temp <- na_percentage(churn_df)
temp
```
```{r}
no_cols <- length(names(temp))

data_frame(index = c(1:no_cols), colnames = names(temp))
```

Looking at observation from columns that have 6.0060% `NA` values. Trying to find a pattern in the way `NA` values are distributed

```{r}
churn_df %>%
  select(6:13, 15:16, 18, 19) %>%
  filter_all(any_vars(is.na(.))) 
```
```{r}
#churn_df_1 <- churn_df[lapply(churn_df, function(x) sum(is.na(x)) / length(x)) >= 0.75]
#churn_df_1 <- churn_df %>%
#  is.na() %>%
#  rowMeans() %>%
#  subset(. <= 0.75)
churn_df_1 <- churn_df[rowMeans(is.na(churn_df)) <= 0.25,]
summary(churn_df_1)
na_percentage(churn_df_1)
#  extract(churn_df, .) 
```

```{r}
tem4_na <- churn_df_1 %>%
  select(6:13, 15:16, 18, 19) %>%
  filter_all(any_vars(is.na(.)))

View(tem4_na)
```

```{r}
tem4_na_dist <- churn_df_1 %>%
  select(6:13, 15:16, 18, 19) %>%
  distinct() %>%
  filter_all(any_vars(is.na(.)))

View(tem4_na_dist)
```


```{r}
model3 <- glm(churn~.,data=churn_df_1,family="binomial")
summary(model3)
```

```{r}
churn_df_2 <- churn_df_1 %>% 
  select(-account_length,-total_intl_calls,-total_eve_minutes)
View(churn_df_2)
```

```{r}
churn_df_3 <- churn_df_1 %>% 
  dplyr::select(-account_length)
```

```{r}
model5 <- glm(churn~.,data=churn_df_3,family="binomial")
summary(model5)
```

```{r}
model4 <- glm(churn~.,data=churn_df_2,family="binomial")
summary(model4)
```

```{r}
library("VIM")
kNN(churn_df_3,variable = c("total_eve_minutes"), k = 4)
##churn_df_3$total_intl_calls <- -kNN(churn_df_3, variable = c("total_intl_calls"), k = 4)

churn_df_3
```

```{r}
churn_df_6 <- churn_df_3 %>%
  dplyr::select(-state, -area_code) %>%
  mutate(churn = revalue(factor(.$churn), c("yes" = "1", "no" = "0")))

churn_df_6
```






```{r}
library(MASS)
churn_d <- churn_df_3[c(-1, -3)]
churn_d <- churn_d[,unlist(lapply(churn_d, is.numeric))]

fit <- lm(churn~., data = churn_d)
summary(fit)
step2 <- step(fit)
summary(step2)
step$anova
```


```{r}
cor(churn_d[,unlist(lapply(churn_d, is.numeric))])
```


## First attempt at cleaning `NA` values per row 
```{r}
complete_fun <- function(data, desired_cols) {
  complete_vec <- complete.cases(data[, desired_cols])
  return(data[complete_vec, ])
}

churn_df %>% 
  sapply (function(x) {
    return (sum(is.na(x)) / length(x)  <= 0.25 )
  })

temp2 <- churn_df %>%
  complete_fun(c(6:13, 15:16, 18, 19))

summary(temp2)

na_percentage(temp2)
```

```{r}
tem2_na <- churn_df %>%
  select(6:13, 15:16, 18, 19) %>%
  filter_all(any_vars(is.na(.)))

View(tem2_na)
```

```{r}
tem2_na_dist <- churn_df %>%
  select(6:13, 15:16, 18, 19) %>%
  distinct() %>%
  filter_all(any_vars(is.na(.)))

View(tem2_na_dist)
```

```{r}
model =glm(churn~.,data=churn_df,family="binomial")
summary(model)
```
```{r}
model1 =glm(churn~.,data=temp2,family="binomial")
summary(model1)
```

```{r}
temp3 <- temp2 %>% 
  select(-account_length)

```

```{r}
model2 <- glm(churn~.,data=temp3,family ="binomial")
summary(model2)
```

